// ============================================================
// lib/platformMap.ts — Platform Distribution Map
// Maps 3 generated images → 17 platform usages
// ============================================================

import type { PlatformUsage, SourceFormat } from './types';

export const PLATFORM_MAP: PlatformUsage[] = [
  // ── From Story Image (9:16) ──────────────────────────────────────────────
  {
    id: 'instagram_story',
    platform: 'Instagram',
    platformAr: 'انستقرام',
    usage: 'Story',
    usageAr: 'ستوري',
    sourceFormat: 'story',
    icon: 'instagram',
    color: '#E1306C',
    hasCaption: true,
    captionKey: 'instagram_story',
  },
  {
    id: 'snapchat_story',
    platform: 'Snapchat',
    platformAr: 'سناب شات',
    usage: 'Story / Snap',
    usageAr: 'ستوري / سناب',
    sourceFormat: 'story',
    icon: 'snapchat',
    color: '#FFFC00',
    hasCaption: true,
    captionKey: 'snapchat',
  },
  {
    id: 'pinterest_pin',
    platform: 'Pinterest',
    platformAr: 'بنترست',
    usage: 'Pin',
    usageAr: 'بن',
    sourceFormat: 'story',
    icon: 'pinterest',
    color: '#E60023',
    hasCaption: true,
    captionKey: 'pinterest',
  },
  {
    id: 'facebook_story',
    platform: 'Facebook',
    platformAr: 'فيسبوك',
    usage: 'Story',
    usageAr: 'ستوري',
    sourceFormat: 'story',
    icon: 'facebook',
    color: '#1877F2',
    hasCaption: true,
    captionKey: 'facebook_story',
  },
  {
    id: 'tiktok_cover',
    platform: 'TikTok',
    platformAr: 'تيك توك',
    usage: 'Cover / Story',
    usageAr: 'غلاف / ستوري',
    sourceFormat: 'story',
    icon: 'tiktok',
    color: '#010101',
    hasCaption: true,
    captionKey: 'tiktok',
  },
  {
    id: 'whatsapp_status',
    platform: 'WhatsApp',
    platformAr: 'واتساب',
    usage: 'Status',
    usageAr: 'حالة',
    sourceFormat: 'story',
    icon: 'whatsapp',
    color: '#25D366',
    hasCaption: true,
    captionKey: 'whatsapp',
  },
  {
    id: 'youtube_shorts',
    platform: 'YouTube',
    platformAr: 'يوتيوب',
    usage: 'Shorts Thumbnail',
    usageAr: 'غلاف شورتس',
    sourceFormat: 'story',
    icon: 'youtube',
    color: '#FF0000',
    hasCaption: false,
    captionKey: 'youtube_shorts',
  },

  // ── From Post Image (1:1) ────────────────────────────────────────────────
  {
    id: 'instagram_post',
    platform: 'Instagram',
    platformAr: 'انستقرام',
    usage: 'Post',
    usageAr: 'بوست',
    sourceFormat: 'post',
    icon: 'instagram',
    color: '#E1306C',
    hasCaption: true,
    captionKey: 'instagram_post',
  },
  {
    id: 'facebook_post',
    platform: 'Facebook',
    platformAr: 'فيسبوك',
    usage: 'Post',
    usageAr: 'بوست',
    sourceFormat: 'post',
    icon: 'facebook',
    color: '#1877F2',
    hasCaption: true,
    captionKey: 'facebook_post',
  },
  {
    id: 'telegram_post',
    platform: 'Telegram',
    platformAr: 'تلقرام',
    usage: 'Post',
    usageAr: 'بوست',
    sourceFormat: 'post',
    icon: 'telegram',
    color: '#0088CC',
    hasCaption: true,
    captionKey: 'telegram',
  },
  {
    id: 'haraj_ad',
    platform: 'Haraj',
    platformAr: 'حراج',
    usage: 'Ad',
    usageAr: 'إعلان',
    sourceFormat: 'post',
    icon: 'haraj',
    color: '#00A859',
    hasCaption: true,
    captionKey: 'haraj',
  },
  {
    id: 'truth_social',
    platform: 'Truth Social',
    platformAr: 'تروث سوشال',
    usage: 'Post',
    usageAr: 'بوست',
    sourceFormat: 'post',
    icon: 'truth',
    color: '#5448EE',
    hasCaption: true,
    captionKey: 'truth_social',
  },

  // ── From Landscape Image (16:9) ──────────────────────────────────────────
  {
    id: 'twitter_post',
    platform: 'Twitter / X',
    platformAr: 'تويتر / إكس',
    usage: 'Tweet',
    usageAr: 'تغريدة',
    sourceFormat: 'landscape',
    icon: 'twitter',
    color: '#1DA1F2',
    hasCaption: true,
    captionKey: 'twitter',
  },
  {
    id: 'linkedin_post',
    platform: 'LinkedIn',
    platformAr: 'لينكد إن',
    usage: 'Post',
    usageAr: 'بوست',
    sourceFormat: 'landscape',
    icon: 'linkedin',
    color: '#0A66C2',
    hasCaption: true,
    captionKey: 'linkedin',
  },
  {
    id: 'youtube_thumbnail',
    platform: 'YouTube',
    platformAr: 'يوتيوب',
    usage: 'Thumbnail',
    usageAr: 'صورة مصغرة',
    sourceFormat: 'landscape',
    icon: 'youtube',
    color: '#FF0000',
    hasCaption: false,
    captionKey: 'youtube_thumbnail',
  },
];

// Group platforms by source format for display
export function groupBySourceFormat(map: PlatformUsage[]): Record<SourceFormat, PlatformUsage[]> {
  return {
    story: map.filter(p => p.sourceFormat === 'story'),
    post: map.filter(p => p.sourceFormat === 'post'),
    landscape: map.filter(p => p.sourceFormat === 'landscape'),
  };
}
